// تعريف بيانات الطعام
var foods = [
    { name: "تفاح", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, quantity: "حبة" },
    { name: "موز", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, quantity: "حبة" },
    { name: "تفاح", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, quantity: "حبة" },
    { name: "موز", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, quantity: "حبة" },
    { name: "رز", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, quantity: "100 جرام" }, // تحديث القيم لتكون لكل 100 جرام
    { name: "برتقال", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, quantity: "حبة" },
    { name: "خوخ", calories: 50, protein: 1.2, carbs: 12, fat: 0.3, quantity: "حبة" },
    { name: "مانجو", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, quantity: "حبة" },
    { name: "بطيخ", calories: 30, protein: 0.6, carbs: 8, fat: 0.2, quantity: "شريحة" },
    { name: "جزر", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, quantity: "جرام" },
    { name: "خيار", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, quantity: "جرام" },
    { name: "طماطم", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, quantity: "جرام" },
    { name: "بطاطا", calories: 77, protein: 2.0, carbs: 17, fat: 0.1, quantity: "جرام" },
    { name: "بيضة", calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3, quantity: "حبة" },
    { name: "لحم الدجاج (مطبوخ)", calories: 239, protein: 27, carbs: 0, fat: 14, quantity: "جرام" },
    { name: "لحم البقر (مطبوخ)", calories: 250, protein: 26, carbs: 0, fat: 15, quantity: "جرام" },
    { name: "جبنة شيدر", calories: 403, protein: 25, carbs: 1.3, fat: 33, quantity: "جرام" },
    { name: "لبنة", calories: 98, protein: 3.5, carbs: 4.1, fat: 8.0, quantity: "جرام" },
    { name: "حليب", calories: 42, protein: 3.4, carbs: 4.8, fat: 1.0, quantity: "كوب" },
    { name: "خبز أبيض", calories: 265, protein: 9, carbs: 49, fat: 3.2, quantity: "قطعة" },
    { name: "خبز الحبوب", calories: 247, protein: 13, carbs: 41, fat: 4.2, quantity: "قطعة" },
    { name: "رز أبيض (مطبوخ)", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, quantity: "جرام" },
    { name: "شعيرية (مطبوخة)", calories: 157, protein: 5.8, carbs: 30, fat: 1.2, quantity: "جرام" },
    { name: "بيتزا", calories: 266, protein: 11, carbs: 33, fat: 10, quantity: "قطعة" },
    { name: "برغر", calories: 295, protein: 17, carbs: 30, fat: 12, quantity: "قطعة" },
    { name: "بطاطس مقلية", calories: 312, protein: 3.4, carbs: 41, fat: 15, quantity: "جرام" },
    { name: "كيك", calories: 237, protein: 2.3, carbs: 28, fat: 12, quantity: "قطعة" },
    { name: "بسكويت", calories: 400, protein: 4.9, carbs: 62, fat: 19, quantity: "قطعة" },
    { name: "حلوى", calories: 392, protein: 0, carbs: 98, fat: 0, quantity: "قطعة" },
    { name: "شوكولاتة", calories: 546, protein: 4.9, carbs: 61, fat: 31, quantity: "قطعة" },
    { name: "فول", calories: 341, protein: 21, carbs: 63, fat: 1.2, quantity: "كوب" },
    { name: "حمص", calories: 164, protein: 8.9, carbs: 27, fat: 2.6, quantity: "كوب" },
    { name: "عدس", calories: 116, protein: 9, carbs: 20, fat: 0.4, quantity: "كوب" },
    { name: "بازيلاء", calories: 81, protein: 5.4, carbs: 14.5, fat: 0.4, quantity: "كوب" },
    { name: "زيتون", calories: 115, protein: 0.8, carbs: 6, fat: 10.7, quantity: "جرام" },
    { name: "بسبوسة", calories: 356, protein: 4.3, carbs: 56, fat: 12.3, quantity: "قطعة" },
    { name: "كنافة", calories: 320, protein: 6.0, carbs: 56, fat: 8.2, quantity: "قطعة" },
    { name: "بقلاوة", calories: 484, protein: 6.1, carbs: 53, fat: 28, quantity: "قطعة" },
    { name: "شاورما دجاج", calories: 195, protein: 24, carbs: 2, fat: 10, quantity: "وجبة" },
    { name: "شاورما لحم", calories: 260, protein: 25, carbs: 2, fat: 16, quantity: "وجبة" },
    { name: "كبة", calories: 320, protein: 16, carbs: 25, fat: 17, quantity: "قطعة" },
    { name: "منسف", calories: 379, protein: 27, carbs: 32, fat: 15, quantity: "وجبة" },
    { name: "مقلوبة", calories: 270, protein: 12, carbs: 36, fat: 10, quantity: "وجبة" },
    { name: "ملوخية", calories: 50, protein: 3.3, carbs: 7, fat: 0.3, quantity: "كوب" },
    { name: "فسيخ", calories: 310, protein: 25, carbs: 0, fat: 22, quantity: "جرام" },
    { name: "سمك مشوي", calories: 195, protein: 40, carbs: 0, fat: 5, quantity: "جرام" },
    { name: "سمك مقلي", calories: 305, protein: 25, carbs: 15, fat: 18, quantity: "جرام" },
    { name: "سمك بالتحمير", calories: 250, protein: 28, carbs: 0, fat: 14, quantity: "جرام" },
    { name: "عصير البرتقال", calories: 120, protein: 1.7, carbs: 29, fat: 0.2, quantity: "كوب" },
    { name: "عصير الليمون", calories: 112, protein: 0.9, carbs: 34, fat: 0.3, quantity: "كوب" },
    { name: "عصير الجزر", calories: 94, protein: 2.2, carbs: 22, fat: 0.2, quantity: "كوب" },
    { name: "عصير الخوخ", calories: 60, protein: 1.2, carbs: 14, fat: 0.4, quantity: "كوب" },
    { name: "عصير المانجو", calories: 120, protein: 0.9, carbs: 31, fat: 0.3, quantity: "كوب" },
    { name: "قهوة عربية", calories: 2, protein: 0, carbs: 0.3, fat: 0, quantity: "كوب" },
    { name: "شاي عربي", calories: 2, protein: 0, carbs: 0.5, fat: 0, quantity: "كوب" },
    { name: "شاي أخضر", calories: 2, protein: 0, carbs: 0.3, fat: 0, quantity: "كوب" },
    { name: "شاي أسود", calories: 2, protein: 0, carbs: 0.4, fat: 0, quantity: "كوب" },
    { name: "ماء", calories: 0, protein: 0, carbs: 0, fat: 0, quantity: "كوب" },
    { name: "عصير تفاح طبيعي", calories: 115, protein: 0.4, carbs: 28, fat: 0.3, quantity: "كوب" },
    { name: "عصير عنب طبيعي", calories: 154, protein: 0.7, carbs: 39, fat: 0.2, quantity: "كوب" },
    { name: "عصير بطيخ طبيعي", calories: 60, protein: 1.0, carbs: 14, fat: 0.3, quantity: "كوب" },
    { name: "عصير توت طبيعي", calories: 60, protein: 0.5, carbs: 15, fat: 0.2, quantity: "كوب" },
    { name: "عصير برتقال طبيعي", calories: 112, protein: 1.7, carbs: 27, fat: 0.2, quantity: "كوب" },
    { name: "عصير جوافة طبيعي", calories: 148, protein: 1.1, carbs: 36, fat: 0.3, quantity: "كوب" },
    { name: "عصير ليمون طبيعي", calories: 61, protein: 0.9, carbs: 20, fat: 0.1, quantity: "كوب" },
    { name: "عصير مانجو طبيعي", calories: 110, protein: 0.8, carbs: 28, fat: 0.2, quantity: "كوب" },
    { name: "عصير كمثرى طبيعي", calories: 96, protein: 0.5, carbs: 25, fat: 0.1, quantity: "كوب" },
    { name: "عصير أناناس طبيعي", calories: 133, protein: 0.9, carbs: 33, fat: 0.2, quantity: "كوب" },
    { name: "عصير بابايا طبيعي", calories: 119, protein: 0.9, carbs: 30, fat: 0.2, quantity: "كوب" },
    { name: "عصير مشمش طبيعي", calories: 60, protein: 0.9, carbs: 15, fat: 0.1, quantity: "كوب" },
    { name: "عصير خوخ طبيعي", calories: 60, protein: 1.0, carbs: 15, fat: 0.1, quantity: "كوب" },
    { name: "عصير تفاح معبأ", calories: 120, protein: 0.4, carbs: 30, fat: 0.2, quantity: "كوب" },
    { name: "عصير عنب معبأ", calories: 154, protein: 0.7, carbs: 39, fat: 0.3, quantity: "كوب" },
    { name: "عصير بطيخ معبأ", calories: 80, protein: 1.0, carbs: 20, fat: 0.2, quantity: "كوب" },
    { name: "عصير توت معبأ", calories: 80, protein: 0.5, carbs: 20, fat: 0.2, quantity: "كوب" },
    { name: "عصير برتقال معبأ", calories: 112, protein: 1.7, carbs: 27, fat: 0.2, quantity: "كوب" },
    { name: "عصير جوافة معبأ", calories: 148, protein: 1.1, carbs: 36, fat: 0.3, quantity: "كوب" },
    { name: "عصير ليمون معبأ", calories: 61, protein: 0.9, carbs: 20, fat: 0.1, quantity: "كوب" },
    { name: "عصير مانجو معبأ", calories: 110, protein: 0.8, carbs: 28, fat: 0.2, quantity: "كوب" },
    { name: "عصير توت بري معبأ", calories: 80, protein: 0.5, carbs: 20, fat: 0.2, quantity: "كوب" },
    { name: "عصير كمثرى معبأ", calories: 96, protein: 0.5, carbs: 25, fat: 0.1, quantity: "كوب" },
    { name: "عصير أناناس معبأ", calories: 133, protein: 0.9, carbs: 33, fat: 0.2, quantity: "كوب" },
    { name: "عصير بابايا معبأ", calories: 119, protein: 0.9, carbs: 30, fat: 0.2, quantity: "كوب" },
    { name: "عصير مشمش معبأ", calories: 80, protein: 0.9, carbs: 20, fat: 0.1, quantity: "كوب" },
    { name: "كبسة", calories: 371, protein: 13, carbs: 45, fat: 15, quantity: "كوب" },
    { name: "مندي", calories: 656, protein: 25, carbs: 87, fat: 24, quantity: "كوب" },
    { name: "كبة", calories: 237, protein: 12, carbs: 18, fat: 13, quantity: "قطعة" },
    { name: "كبسة العدس", calories: 152, protein: 8, carbs: 20, fat: 5, quantity: "كوب" },
    { name: "فتة", calories: 356, protein: 18, carbs: 45, fat: 14, quantity: "كوب" },
    { name: "رز مع اللحم", calories: 296, protein: 14, carbs: 38, fat: 9, quantity: "كوب" },
    { name: "رز بالخضار", calories: 157, protein: 4, carbs: 28, fat: 3, quantity: "كوب" },
    { name: "شاورما", calories: 490, protein: 24, carbs: 40, fat: 25, quantity: "قطعة" },
    { name: "برياني", calories: 474, protein: 24, carbs: 45, fat: 22, quantity: "كوب" },
    { name: "حمص", calories: 296, protein: 19, carbs: 45, fat: 9, quantity: "كوب" },
    { name: "فلافل", calories: 57, protein: 2.3, carbs: 7.5, fat: 3, quantity: "قطعة" },
    { name: "مطبق", calories: 200, protein: 6, carbs: 20, fat: 10, quantity: "قطعة" },
    { name: "كعك العيد", calories: 89, protein: 1.1, carbs: 15, fat: 3.5, quantity: "قطعة" },
    { name: "كبسة بالدجاج", calories: 218, protein: 14, carbs: 20, fat: 10, quantity: "كوب" },
    { name: "رز بالمكسرات", calories: 278, protein: 6, carbs: 40, fat: 10, quantity: "كوب" },
    { name: "مسبح", calories: 320, protein: 14, carbs: 30, fat: 15, quantity: "قطعة" },
    { name: "صالونة", calories: 170, protein: 10, carbs: 15, fat: 8, quantity: "قطعة" },
    { name: "حلاوة طحينية", calories: 220, protein: 5, carbs: 35, fat: 10, quantity: "قطعة" },
    { name: "مرقوق", calories: 300, protein: 8, carbs: 45, fat: 10, quantity: "قطعة" },
    { name: "لقيمات", calories: 100, protein: 2, carbs: 16, fat: 4, quantity: "قطعة" },
    { name: "كبة مشلتت", calories: 300, protein: 12, carbs: 20, fat: 18, quantity: "قطعة" },
    { name: "حلاوة بنجابية", calories: 200, protein: 3, carbs: 30, fat: 9, quantity: "قطعة" },
    { name: "تميس", calories: 250, protein: 6, carbs: 48, fat: 3, quantity: "قطعة" },
    { name: "سمبوسة", calories: 150, protein: 3, carbs: 15, fat: 9, quantity: "قطعة" },
    { name: "مكبوس دجاج", calories: 310, protein: 24, carbs: 35, fat: 10, quantity: "قطعة" },
    { name: "عصيدة", calories: 220, protein: 6, carbs: 40, fat: 5, quantity: "كوب" },
    { name: "صامولي", calories: 250, protein: 8, carbs: 48, fat: 3, quantity: "قطعة" },
    { name: "حمص بالطحينة", calories: 100, protein: 5, carbs: 8, fat: 6, quantity: "قطعة" },
    { name: "المعصوب", calories: 500, protein: 8, carbs: 90, fat: 12, quantity: "قطعة" },
    { name: "جريش", calories: 200, protein: 6, carbs: 30, fat: 7, quantity: "كوب" } ,
    { name: "لوز", calories: 575, protein: 21, carbs: 22, fat: 49, quantity: "100 جرام" },
    { name: "جوز", calories: 654, protein: 15, carbs: 14, fat: 65, quantity: "100 جرام" },
    { name: "بندق", calories: 628, protein: 15, carbs: 17, fat: 61, quantity: "100 جرام" },
    { name: "كاجو", calories: 553, protein: 18, carbs: 30, fat: 44, quantity: "100 جرام" },
    { name: "فستق", calories: 557, protein: 21, carbs: 28, fat: 44, quantity: "100 جرام" },
    { name: "مكاديميا", calories: 718, protein: 8, carbs: 14, fat: 76, quantity: "100 جرام" },
    { name: "جوز البرازيل", calories: 656, protein: 14, carbs: 12, fat: 66, quantity: "100 جرام" },
    { name: "جوز البيكان", calories: 691, protein: 9, carbs: 14, fat: 72, quantity: "100 جرام" },
    { name: "صنوبر", calories: 673, protein: 14, carbs: 13, fat: 68, quantity: "100 جرام" },
    { name: "جوز الهند", calories: 354, protein: 3, carbs: 15, fat: 33, quantity: "100 جرام" },
    { name: "بذور دوار الشمس", calories: 584, protein: 21, carbs: 20, fat: 51, quantity: "100 جرام" },
    { name: "بذور اليقطين", calories: 559, protein: 30, carbs: 10, fat: 49, quantity: "100 جرام" },
    { name: "بذور السمسم", calories: 573, protein: 18, carbs: 23, fat: 50, quantity: "100 جرام" },
    { name: "بذور الشيا", calories: 486, protein: 17, carbs: 42, fat: 31, quantity: "100 جرام" },
    { name: "بذور الكتان", calories: 534, protein: 18, carbs: 29, fat: 42, quantity: "100 جرام" },
    { name: "سمك السلمون المشوي", calories: 206, protein: 22.5, carbs: 0, fat: 12.5, quantity: "جرام" },
    { name: "أفوكادو", calories: 160, protein: 2, carbs: 9, fat: 15, quantity: "حبة" },
    { name: "دجاج مشوي", calories: 165, protein: 31, carbs: 0, fat: 3.6, quantity: "جرام" },
    { name: "تونة معلبة في الماء", calories: 100, protein: 22, carbs: 0, fat: 1, quantity: "جرام" },
    { name: "زبادي طبيعي", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, quantity: "كوب" },
    { name: "فطر", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, quantity: "كوب" },
    { name: "لوز", calories: 575, protein: 21, carbs: 22, fat: 49, quantity: "جرام" },
    { name: "جوز", calories: 654, protein: 15, carbs: 14, fat: 65, quantity: "جرام" },
    { name: "فول الصويا المطبوخ", calories: 173, protein: 18, carbs: 10, fat: 9, quantity: "كوب" },
    { name: "توفو", calories: 70, protein: 8, carbs: 1.9, fat: 4.2, quantity: "جرام" },
    { name: "شوفان", calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9, quantity: "كوب" },
    { name: "موسلي", calories: 289, protein: 8, carbs: 66, fat: 4.9, quantity: "كوب" },
    { name: "تمر", calories: 277, protein: 1.8, carbs: 75, fat: 0.2, quantity: "جرام" },
    { name: "فلفل أحمر", calories: 31, protein: 1, carbs: 6, fat: 0.3, quantity: "حبة" },
    { name: "بطاطس مسلوقة", calories: 87, protein: 1.9, carbs: 20, fat: 0.1, quantity: "جرام" },
    { name: "بطاطس مشوية", calories: 93, protein: 2.5, carbs: 21, fat: 0.1, quantity: "جرام" },
    { name: "عسل طبيعي", calories: 304, protein: 0.3, carbs: 82, fat: 0, quantity: "جرام" },
    { name: "شوكولاتة داكنة", calories: 546, protein: 5, carbs: 61, fat: 31, quantity: "جرام" },
    { name: "كينوا", calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9, quantity: "جرام" },
    { name: "فلفل حار", calories: 40, protein: 2, carbs: 9, fat: 0.4, quantity: "جرام" }
    // أضف المزيد من الطعام حسب الحاجة

    ];

// وظائف حسابية للسعرات الحرارية والبروتين والكربوهيدرات والدهون
function calculateFoodNutrients(foodName, quantity, unit) {
    var found = foods.find(food => food.name === foodName);
    if (found) {
        var multiplier = 1; // معامل التحويل بناءً على الوحدة
        if (unit === "kilogram") {
            multiplier = 10; // للتحويل من كيلوغرام إلى 100 جرام
        } else if (unit === "gram") {
            multiplier = quantity / 100;
        } else if (unit === "piece" && found.quantity !== "جرام") {
            multiplier = quantity;
        }

        return {
            calories: found.calories * multiplier,
            proteins: found.protein * multiplier,
            carbs: found.carbs * multiplier,
            fats: found.fat * multiplier
        };
    }
    return null; // إذا لم يتم العثور على الطعام
}
